version: "2"
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
     - ./uploads:/app/uploads
     - ./api/src:/app/src
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
    mongodata: {}
    uploads: {}
    